import {Game,onPath,towerStats} from '../src/engine.mjs';
import {MAPS,HEROES,WIDTH,HEIGHT} from '../src/data.mjs';
function bestSpot(g,hero){const h=HEROES.find(h=>h.id===hero);let best=null,bestScore=-Infinity;const samples=MAPS[g.map].paths.map((p,i)=>Array.from({length:Math.floor(g.lengths[i]/65)},(_,j)=>({...onPath(p,j*65),progress:j*65/g.lengths[i]})));
 for(let y=90;y<HEIGHT-100;y+=70)for(let x=90;x<WIDTH-80;x+=70){if(!g.canPlace(x,y))continue;let score=0;const routeCoverage=[];for(const path of samples){let coverage=0;for(const p of path)if(Math.hypot(x-p.x,y-p.y)<h.range)coverage+=1+(p.progress>.25&&p.progress<.75?.35:0);routeCoverage.push(coverage);score+=coverage}if(routeCoverage.length>1&&routeCoverage.every(x=>x>0))score*=1.5;if(hero==='captain')score+=g.towers.filter(t=>Math.hypot(t.x-x,t.y-y)<h.range).length*7;score-=g.towers.filter(t=>Math.hypot(t.x-x,t.y-y)<100).length*.7;if(score>bestScore){bestScore=score;best={x,y}}}return best}
export function simulateMission(map,difficulty='heroic'){
 const g=new Game({map,difficulty});const ids={};const build=[];const place=(hero,key=hero)=>build.push({hero,key});const up=(key,b,n=1)=>{for(let i=0;i<n;i++)build.push({key,b})};
 place('ironman');place('spiderman');place('strange');up('strange',0);up('ironman',0);up('spiderman',0,2);up('strange',0);up('ironman',0);place('captain');up('captain',1);up('ironman',1,2);up('ironman',0);up('spiderman',0);up('strange',0);place('panther');up('panther',1,2);up('captain',1,2);up('ironman',0);up('strange',1,2);up('captain',1);up('captain',0,2);place('thor');up('thor',1,4);up('thor',0,2);up('spiderman',0);up('spiderman',1,2);up('strange',0);up('panther',1,2);up('panther',0,2);place('hulk');up('hulk',1,4);up('hulk',0,2);place('wanda');up('wanda',0,4);up('wanda',1,2);place('thor','thor2');up('thor2',1,4);up('thor2',0,2);place('ironman','iron2');up('iron2',1,4);up('iron2',0,2);
 let pointer=0;const waves=[];for(let wave=1;wave<=MAPS[map].waves;wave++){while(pointer<build.length){const task=build[pointer];if(task.hero){const h=HEROES.find(h=>h.id===task.hero);if(g.cash<h.cost)break;const pos=bestSpot(g,task.hero);if(!pos)break;const t=g.place(task.hero,pos.x,pos.y);if(!t)throw Error('Bad placement');ids[task.key]=t.id;}else{if(!g.upgrade(ids[task.key],task.b))break;}pointer++}
  g.startWave();let ticks=0;while(g.status==='wave'&&ticks<60*220){if(ticks%30===0)for(const t of g.towers)if(t.ability<=0&&Math.max(...t.upgrades)>=3&&g.enemies.some(e=>Math.hypot(e.x-t.x,e.y-t.y)<towerStats(t).range)&&(g.enemies.length>12||g.enemies.some(e=>e.type==='loki'||e.type==='ultron'||e.type==='thanos')))g.ability(t.id);g.step(1/30);g.events.length=0;ticks++}waves.push({wave:g.wave,lives:g.lives,cash:g.cash,kills:g.kills,seconds:Math.round(ticks/30),towers:g.towers.length});if(g.status==='defeat'||ticks>=60*220)break;
 }return{map:MAPS[map].name,difficulty,status:g.status,wave:g.wave,lives:g.lives,cash:g.cash,kills:g.kills,buildSteps:pointer,escapedBoss:g.enemies.filter(e=>e.type==='thanos').map(e=>({hp:Math.round(e.hp),maxHp:e.maxHp})),waves,towers:g.towers.map(t=>({hero:t.hero,upgrades:t.upgrades,damage:Math.round(t.damage),kills:t.kills,x:t.x,y:t.y}))};
}
if(process.argv[1]?.endsWith('balance.mjs')){const results=[];for(const difficulty of process.argv.includes('--all')?['story','heroic','legendary']:['heroic'])for(let m=0;m<6;m++){const r=simulateMission(m,difficulty);results.push(r);console.log(JSON.stringify({...r,waves:undefined,towers:undefined}))}if(process.argv.includes('--report')){const {writeFile}=await import('node:fs/promises');await writeFile(new URL('../BALANCE-REPORT.json',import.meta.url),JSON.stringify(results,null,2));}}
