import {VERSION,WIDTH,HEIGHT,HEROES,ENEMIES,MAPS,DIFFICULTIES,wavePlan} from './data.mjs';
export function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
export function pathLength(path){let total=0;for(let i=1;i<path.length;i++)total+=Math.hypot(path[i][0]-path[i-1][0],path[i][1]-path[i-1][1]);return total}
export function onPath(path,d){for(let i=1;i<path.length;i++){const [x,y]=path[i-1],dx=path[i][0]-x,dy=path[i][1]-y,len=Math.hypot(dx,dy);if(d<=len)return{x:x+dx*d/len,y:y+dy*d/len,angle:Math.atan2(dy,dx)};d-=len}const p=path.at(-1);return{x:p[0],y:p[1],angle:0}}
export function distanceToPath(x,y,path){let result=Infinity;for(let i=1;i<path.length;i++){let [ax,ay]=path[i-1],[bx,by]=path[i],dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy)));result=Math.min(result,Math.hypot(x-ax-t*dx,y-ay-t*dy))}return result}
export function towerStats(t){const hero=HEROES.find(h=>h.id===t.hero);const s={damage:hero.damage,range:hero.range,rate:hero.rate,shots:1,chain:1,splash:0,pierce:0,detect:false,slow:0,slowTime:0,stun:0,dot:0,vulnerable:0,push:0,boss:0,aura:0,auraRate:0,auraDetect:false,income:0};for(const k of Object.keys(s))if(hero[k]!==undefined)s[k]=hero[k];for(let b=0;b<2;b++)for(let j=0;j<t.upgrades[b];j++)for(const[k,v]of Object.entries(hero.branches[b].upgrades[j].mods)){if(typeof v==='boolean')s[k]=v;else if(k==='rate')s[k]*=v;else s[k]+=v}return s}
export function upgradeState(t,branch,cash){const level=t.upgrades[branch],other=t.upgrades[1-branch];if(level>=4)return{allowed:false,reason:'Branch complete'};if(level>=2&&other>=3)return{allowed:false,reason:'Other specialization chosen'};const upgrade=HEROES.find(h=>h.id===t.hero).branches[branch].upgrades[level];return{allowed:cash>=upgrade.cost,reason:cash<upgrade.cost?'Insufficient credits':'',upgrade}}
export class Game{
 constructor({map=0,difficulty='heroic',mode='campaign',seed=12345}={}){this.map=map;this.difficulty=difficulty;this.mode=mode;this.seed=seed;this.cash=mode==='sandbox'?999999:DIFFICULTIES[difficulty].cash;this.lives=DIFFICULTIES[difficulty].lives;this.maxLives=this.lives;this.wave=0;this.status='build';this.towers=[];this.enemies=[];this.events=[];this.plan=[];this.waveTime=0;this.time=0;this.nextId=1;this.kills=0;this.spent=0;this.earned=0;this.leaks=0;this.boost=0;this.auto=false;this.autoTimer=0;this.completed=false;this.totalDamage=0;this.difficultyScale=1+map*.08;this.lengths=MAPS[map].paths.map(pathLength)}
 event(type,data={}){this.events.push({type,...data});if(this.events.length>600)this.events.shift()}
 random(){this.seed=(Math.imul(1664525,this.seed)+1013904223)>>>0;return this.seed/4294967296}
 canPlace(x,y){if(!Number.isFinite(x)||!Number.isFinite(y)||x<36||x>WIDTH-36||y<45||y>HEIGHT-36)return false;if(MAPS[this.map].theme==='city'&&y>HEIGHT-110)return false;if(MAPS[this.map].paths.some(p=>distanceToPath(x,y,p)<52))return false;if(this.towers.some(t=>Math.hypot(x-t.x,y-t.y)<70))return false;return !MAPS[this.map].decor.some(([a,b,w,h])=>x>a-24&&x<a+w+24&&y>b-24&&y<b+h+24)}
 place(heroId,x,y){if(!['build','wave'].includes(this.status))return null;const hero=HEROES.find(h=>h.id===heroId);if(!hero||this.cash<hero.cost||!this.canPlace(x,y)||this.towers.length>=40)return null;const t={id:this.nextId++,hero:heroId,x,y,upgrades:[0,0],spent:hero.cost,cooldown:0,ability:0,disabled:0,kills:0,damage:0,target:'first',angle:-Math.PI/2};this.towers.push(t);this.cash-=hero.cost;this.spent+=hero.cost;this.event('place',{x,y,color:hero.color});return t}
 upgrade(id,branch){if(![0,1].includes(branch)||!['build','wave'].includes(this.status))return false;const t=this.towers.find(t=>t.id===id);if(!t)return false;const state=upgradeState(t,branch,this.cash);if(!state.allowed)return false;this.cash-=state.upgrade.cost;t.spent+=state.upgrade.cost;this.spent+=state.upgrade.cost;t.upgrades[branch]++;this.event('upgrade',{x:t.x,y:t.y});return true}
 sell(id){if(!['build','wave'].includes(this.status))return 0;const t=this.towers.find(t=>t.id===id);if(!t)return 0;const refund=Math.floor(t.spent*7/10);this.cash+=refund;this.towers=this.towers.filter(x=>x.id!==id);this.event('sell',{x:t.x,y:t.y,refund});return refund}
 startWave(){if(this.status!=='build')return false;this.wave++;this.waveTime=0;this.plan=wavePlan(this.wave,this.map);this.status='wave';this.autoTimer=0;this.event('wave',{wave:this.wave});return true}
 spawn(type,route=0,d=0){if(this.enemies.length>=500)return;const base=ENEMIES[type];const endScale=Math.min(1e5,1.095**Math.max(0,this.wave-30));const scale=(1+(Math.min(this.wave,30)-1)*.135)*this.difficultyScale*DIFFICULTIES[this.difficulty].hp*endScale;const hp=Math.round(Math.min(1e9,base.hp*(base.boss?Math.max(1,(this.wave/10)*.44)*this.difficultyScale*DIFFICULTIES[this.difficulty].hp*endScale:scale)));const p=onPath(MAPS[this.map].paths[route],d);this.enemies.push({id:this.nextId++,type,route,d,...p,hp,maxHp:hp,slow:0,slowTime:0,stun:0,dot:0,dotTime:0,vulnerable:0,curseTime:0,power:8,source:null,dead:false});if(base.boss)this.event('boss',{name:base.name})}
 damageEnemy(e,amount,t=null,pierce=false){if(e.dead||!Number.isFinite(amount)||amount<=0)return;const def=ENEMIES[e.type];const damage=Math.min(e.hp,amount*(pierce?1:1-(def.armor||0))*(1+e.vulnerable));e.hp-=damage;this.totalDamage+=damage;if(t)t.damage+=damage;if(e.hp<=0){e.dead=true;this.kills++;if(t)t.kills++;const reward=Math.round(def.reward*DIFFICULTIES[this.difficulty].reward);this.cash+=reward;this.earned+=reward;this.event('kill',{x:e.x,y:e.y,color:def.color,boss:!!def.boss,reward});}}
 hit(e,t,s,factor=1){const def=ENEMIES[e.type];this.damageEnemy(e,s.damage*factor*(def.boss?1+s.boss:1),t,s.pierce>0);if(e.dead)return;const resistance=def.boss?.3:1;if(s.slow){e.slow=Math.max(e.slow,Math.min(.85,s.slow)*resistance);e.slowTime=Math.max(e.slowTime,s.slowTime)}e.stun=Math.max(e.stun,s.stun*resistance);if(s.dot){e.dot=Math.max(e.dot,s.dot);e.dotTime=3;e.source=t.id}if(s.vulnerable){e.vulnerable=Math.max(e.vulnerable,s.vulnerable);e.curseTime=4}if(s.push){e.d=Math.max(0,e.d-s.push*resistance);Object.assign(e,onPath(MAPS[this.map].paths[e.route],e.d))}}
 ability(id){const t=this.towers.find(t=>t.id===id);if(!t||this.status!=='wave'||t.ability>0||t.disabled>0||Math.max(...t.upgrades)<3)return false;const hero=HEROES.find(h=>h.id===t.hero);t.ability=hero.ability.cooldown;this.event('ability',{x:t.x,y:t.y,color:hero.color,name:hero.ability.name,hero:t.hero,towerId:t.id,radius:t.hero==='hulk'?280:240});const abilityTargets=this.enemies.map(e=>({id:e.id,x:e.x,y:e.y}));switch(t.hero){
  case'ironman':this.boost=9;break;
  case'captain':for(const e of this.enemies)e.stun=Math.max(e.stun,ENEMIES[e.type].boss?1:3);this.lives=Math.min(this.maxLives,this.lives+8);break;
  case'thor':for(const e of this.enemies)this.damageEnemy(e,450,t,true);break;
  case'spiderman':for(const e of this.enemies){e.slow=ENEMIES[e.type].boss?.45:.85;e.slowTime=7}break;
  case'strange':for(const e of this.enemies){e.d=Math.max(0,e.d-(ENEMIES[e.type].boss?60:160));e.stun=ENEMIES[e.type].boss?.7:2;Object.assign(e,onPath(MAPS[this.map].paths[e.route],e.d))}break;
  case'wanda':for(const e of this.enemies){this.damageEnemy(e,250,t,true);e.vulnerable=.75;e.curseTime=10}break;
  case'panther':case'hulk':for(const e of this.enemies)if(distance(t,e)<(t.hero==='hulk'?280:240)){this.damageEnemy(e,t.hero==='hulk'?950:600,t,true);e.stun=ENEMIES[e.type].boss?.6:2}break;
 }for(const target of abilityTargets){const e=this.enemies.find(e=>e.id===target.id);if(!e)continue;if(['hulk','panther'].includes(t.hero)&&distance(t,e)>280)continue;this.event('ability-impact',{x:e.x,y:e.y,fromX:target.x,fromY:target.y,hero:t.hero,color:hero.color,targetEffect:true})}return true}
 step(dt){if(!Number.isFinite(dt)||dt<=0||dt>.25||!['build','wave'].includes(this.status))return;this.time+=dt;
  if(this.status==='build'){if(this.auto&&this.wave>0){this.autoTimer+=dt;if(this.autoTimer>=3)this.startWave()}return}
  this.waveTime+=dt;this.boost=Math.max(0,this.boost-dt);while(this.plan.length&&this.plan[0].at<=this.waveTime){const p=this.plan.shift();this.spawn(p.type,p.route)}
  for(const e of [...this.enemies]){if(e.dead)continue;const def=ENEMIES[e.type];e.stun=Math.max(0,e.stun-dt);e.slowTime=Math.max(0,e.slowTime-dt);if(!e.slowTime)e.slow=0;e.curseTime=Math.max(0,e.curseTime-dt);if(!e.curseTime)e.vulnerable=0;
   if(e.dotTime>0){e.dotTime-=dt;this.damageEnemy(e,e.dot*dt,this.towers.find(t=>t.id===e.source),true)}if(e.dead)continue;
   if(def.regen)e.hp=Math.min(e.maxHp,e.hp+def.regen*dt);
   if(e.stun<=0)e.d+=def.speed*DIFFICULTIES[this.difficulty].speed*(1-e.slow)*dt;
   Object.assign(e,onPath(MAPS[this.map].paths[e.route],e.d));
   if(def.boss){e.power-=dt;if(e.power<=0){e.power=8;if(e.type==='thanos'){for(const t of this.towers)if(distance(t,e)<250)t.disabled=2;this.event('pulse',{x:e.x,y:e.y,color:def.color})}else if((e.summons||0)<3){e.summons=(e.summons||0)+1;for(let j=0;j<2;j++)this.spawn(e.type==='loki'?'cloak':'armor',e.route,Math.max(0,e.d-j*25))}}}
   if(e.d>=this.lengths[e.route]){e.dead=true;this.lives=Math.max(0,this.lives-def.leak);this.leaks+=def.leak;this.event('leak',{x:e.x,y:e.y});if(this.lives<=0&&this.mode!=='sandbox'){this.status='defeat';this.event('defeat');return}}
  }
  const stats=new Map(this.towers.map(t=>[t.id,towerStats(t)]));
  for(const t of this.towers){t.ability=Math.max(0,t.ability-dt);t.disabled=Math.max(0,t.disabled-dt);t.flash=Math.max(0,(t.flash||0)-dt);t.cooldown-=dt;if(t.cooldown>0||t.disabled>0)continue;const s={...stats.get(t.id)};let damageAura=0,rateAura=0;for(const ally of this.towers){if(ally.id===t.id||ally.disabled>0)continue;const a=stats.get(ally.id);if(distance(t,ally)<=a.range){damageAura=Math.max(damageAura,a.aura);rateAura=Math.max(rateAura,a.auraRate);if(a.auraDetect)s.detect=true}}
   s.damage*=1+damageAura;s.rate*=1-rateAura;if(this.boost>0)s.rate*=.5;
   const candidates=this.enemies.filter(e=>!e.dead&&distance(t,e)<=s.range&&(!ENEMIES[e.type].cloak||s.detect));
   candidates.sort((a,b)=>t.target==='strong'?b.hp-a.hp:t.target==='close'?distance(t,a)-distance(t,b):t.target==='last'?(a.d/this.lengths[a.route])-(b.d/this.lengths[b.route]):(b.d/this.lengths[b.route])-(a.d/this.lengths[a.route]));
   if(!candidates.length)continue;t.cooldown=Math.max(.07,s.rate);t.flash=.22;const hero=HEROES.find(h=>h.id===t.hero);const hitIds=new Set();
   for(const e of candidates.slice(0,s.shots)){if(e.dead)continue;t.angle=Math.atan2(e.y-t.y,e.x-t.x);this.event('attack',{x:t.x,y:t.y,tx:e.x,ty:e.y,color:hero.color,style:hero.style,splash:s.splash,hero:t.hero,towerId:t.id});this.hit(e,t,s);hitIds.add(e.id);
    if(s.splash>0)for(const nearby of this.enemies)if(!nearby.dead&&nearby.id!==e.id&&distance(nearby,e)<s.splash){this.hit(nearby,t,s,.8);hitIds.add(nearby.id)}
    if(s.chain>1){let prev=e;for(let i=1;i<s.chain;i++){const next=this.enemies.filter(x=>!x.dead&&!hitIds.has(x.id)&&(!ENEMIES[x.type].cloak||s.detect)&&distance(x,prev)<135).sort((a,b)=>distance(a,prev)-distance(b,prev))[0];if(!next)break;this.event('attack',{x:prev.x,y:prev.y,tx:next.x,ty:next.y,color:hero.color,style:hero.style,hero:t.hero,towerId:t.id,chain:true});this.hit(next,t,s,Math.max(.45,1-i*.1));hitIds.add(next.id);prev=next;}}
   }
  }
  this.enemies=this.enemies.filter(e=>!e.dead);
  if(this.plan.length===0&&this.enemies.length===0){const income=this.towers.reduce((n,t)=>n+towerStats(t).income,0);const bonus=100+this.wave*16+income;this.cash+=bonus;this.earned+=bonus;this.status='build';this.event('clear',{wave:this.wave,bonus,income});if(this.mode==='campaign'&&this.wave>=MAPS[this.map].waves){this.status='victory';this.completed=true;this.event('victory')}}
 }
 serialize(){const{events,lengths,...state}=this;return JSON.stringify({version:VERSION,state})}
 static restore(raw){try{const obj=JSON.parse(raw),s=obj.state;if(obj.version!==VERSION||!s||!Number.isInteger(s.map)||!MAPS[s.map]||!Object.hasOwn(DIFFICULTIES,s.difficulty)||!['campaign','endless','sandbox'].includes(s.mode)||!['build','wave','victory','defeat'].includes(s.status))return null;
  for(const k of ['cash','lives','maxLives','wave','time','waveTime','nextId','kills','spent','earned','leaks','boost','autoTimer','totalDamage'])if(!Number.isFinite(s[k])||s[k]<0||s[k]>1e12)return null;
  if(s.wave>10000||!Array.isArray(s.towers)||s.towers.length>40||!Array.isArray(s.enemies)||s.enemies.length>500||!Array.isArray(s.plan)||s.plan.length>50000)return null;
  const g=new Game(s);const ids=new Set();for(const t of s.towers){if(!HEROES.some(h=>h.id===t.hero)||!Array.isArray(t.upgrades)||t.upgrades.length!==2||t.upgrades.some(n=>!Number.isInteger(n)||n<0||n>4)||(t.upgrades[0]>2&&t.upgrades[1]>2)||!['first','last','strong','close'].includes(t.target)||!g.canPlace(t.x,t.y)||ids.has(t.id))return null;for(const k of ['id','spent','cooldown','ability','disabled','kills','damage','angle'])if(!Number.isFinite(t[k]))return null;ids.add(t.id);g.towers.push(t)}
  for(const e of s.enemies){if(!Object.hasOwn(ENEMIES,e.type)||!Number.isInteger(e.route)||!MAPS[s.map].paths[e.route]||ids.has(e.id))return null;for(const k of ['id','d','x','y','hp','maxHp','slow','slowTime','stun','dot','dotTime','vulnerable','curseTime','power'])if(!Number.isFinite(e[k]))return null;if(e.hp<=0||e.maxHp<=0||e.d<0)return null;ids.add(e.id)}for(const p of s.plan)if(!Object.hasOwn(ENEMIES,p.type)||!Number.isFinite(p.at)||!Number.isInteger(p.route)||!MAPS[s.map].paths[p.route])return null;
  for(const key of Object.keys(g))if(key!=='events'&&key!=='lengths'&&Object.hasOwn(s,key))g[key]=s[key];g.events=[];g.lengths=MAPS[g.map].paths.map(pathLength);return g;
 }catch{return null}}
}
